var modules =
[
    [ "Asynchronous jobs", "da/d6b/group__jobs.html", "da/d6b/group__jobs" ],
    [ "Guilib classes", "d4/dee/group__guilib.html", "d4/dee/group__guilib" ],
    [ "Database", "df/db7/group__database.html", "df/db7/group__database" ],
    [ "Filesystem", "d6/da4/group__filesystem.html", "d6/da4/group__filesystem" ],
    [ "Input", "dc/df1/group__input.html", "dc/df1/group__input" ],
    [ "Games", "de/dfb/group__games.html", "de/dfb/group__games" ],
    [ "Interfaces", "d8/d60/group__interface.html", "d8/d60/group__interface" ],
    [ "Listproviders", "d3/daf/group__listproviders.html", "d3/daf/group__listproviders" ],
    [ "Music info", "d8/df5/group__music.html", "d8/df5/group__music" ],
    [ "Settings", "d0/de9/group__settings.html", "d0/de9/group__settings" ],
    [ "Windows", "da/d9b/group__windows.html", "da/d9b/group__windows" ],
    [ "C++", "d1/ddf/group__cpp.html", "d1/ddf/group__cpp" ],
    [ "Python", "de/d69/group__python.html", "de/d69/group__python" ],
    [ "class AudioEncoderInfoTag", "de/dfd/group__cpp__kodi__addon__audioencoder___defs___audio_encoder_info_tag.html", "de/dfd/group__cpp__kodi__addon__audioencoder___defs___audio_encoder_info_tag" ],
    [ "Value Help", "d6/d17/group__cpp__kodi__addon__peripheral___defs___peripheral_capabilities___help.html", null ],
    [ "Value Help", "d0/d00/group__cpp__kodi__addon__peripheral___defs___peripheral___peripheral___help.html", null ],
    [ "Value Help", "d0/de9/group__cpp__kodi__addon__peripheral___defs___peripheral___peripheral_event___help.html", null ],
    [ "Value Help", "d4/d50/group__cpp__kodi__addon__peripheral___defs___joystick___joystick___help.html", null ],
    [ "Value Help", "d6/d0f/group__cpp__kodi__addon__pvr___defs___p_v_r_capabilities___help.html", null ],
    [ "Value Help", "dd/db1/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_stream_properties___help.html", null ],
    [ "Value Help", "d7/d72/group__cpp__kodi__addon__pvr___defs___stream___p_v_r_stream_times___help.html", null ],
    [ "Value Help", "de/d29/group__cpp__kodi__addon__pvr___defs___timer___p_v_r_timer_type___help.html", null ],
    [ "Value Help", "df/d28/group__cpp__kodi__vfs___defs___file_status___help.html", null ],
    [ "Value Help", "d3/d14/group__cpp__kodi__vfs___defs___cache_status___help.html", null ],
    [ "Value Help", "db/dcb/group__cpp__kodi__vfs___c_dir_entry___help.html", null ],
    [ "List of sort methods", "d1/d7e/group___list__of__sort__methods.html", "d1/d7e/group___list__of__sort__methods" ]
];