var namespace_v_a_a_p_i =
[
    [ "CDecoder", "d7/dba/class_v_a_a_p_i_1_1_c_decoder.html", "d7/dba/class_v_a_a_p_i_1_1_c_decoder" ],
    [ "CFFmpegPostproc", "d4/db1/class_v_a_a_p_i_1_1_c_f_fmpeg_postproc.html", "d4/db1/class_v_a_a_p_i_1_1_c_f_fmpeg_postproc" ],
    [ "COutput", "dd/d21/class_v_a_a_p_i_1_1_c_output.html", "dd/d21/class_v_a_a_p_i_1_1_c_output" ],
    [ "COutputControlProtocol", "db/dd3/class_v_a_a_p_i_1_1_c_output_control_protocol.html", "db/dd3/class_v_a_a_p_i_1_1_c_output_control_protocol" ],
    [ "COutputDataProtocol", "d3/de7/class_v_a_a_p_i_1_1_c_output_data_protocol.html", "d3/de7/class_v_a_a_p_i_1_1_c_output_data_protocol" ],
    [ "CPostproc", "d4/d2f/class_v_a_a_p_i_1_1_c_postproc.html", "d4/d2f/class_v_a_a_p_i_1_1_c_postproc" ],
    [ "CSkipPostproc", "da/df0/class_v_a_a_p_i_1_1_c_skip_postproc.html", "da/df0/class_v_a_a_p_i_1_1_c_skip_postproc" ],
    [ "CVaapi1Texture", "dd/d2a/class_v_a_a_p_i_1_1_c_vaapi1_texture.html", "dd/d2a/class_v_a_a_p_i_1_1_c_vaapi1_texture" ],
    [ "CVaapi2Texture", "da/d2f/class_v_a_a_p_i_1_1_c_vaapi2_texture.html", "da/d2f/class_v_a_a_p_i_1_1_c_vaapi2_texture" ],
    [ "CVaapiBufferPool", "d3/de8/class_v_a_a_p_i_1_1_c_vaapi_buffer_pool.html", "d3/de8/class_v_a_a_p_i_1_1_c_vaapi_buffer_pool" ],
    [ "CVaapiBufferStats", "d1/d04/class_v_a_a_p_i_1_1_c_vaapi_buffer_stats.html", "d1/d04/class_v_a_a_p_i_1_1_c_vaapi_buffer_stats" ],
    [ "CVaapiConfig", "d0/d1a/struct_v_a_a_p_i_1_1_c_vaapi_config.html", "d0/d1a/struct_v_a_a_p_i_1_1_c_vaapi_config" ],
    [ "CVAAPIContext", "d2/db3/class_v_a_a_p_i_1_1_c_v_a_a_p_i_context.html", "d2/db3/class_v_a_a_p_i_1_1_c_v_a_a_p_i_context" ],
    [ "CVaapiDecodedPicture", "dc/d60/struct_v_a_a_p_i_1_1_c_vaapi_decoded_picture.html", "dc/d60/struct_v_a_a_p_i_1_1_c_vaapi_decoded_picture" ],
    [ "CVaapiProcessedPicture", "df/da2/struct_v_a_a_p_i_1_1_c_vaapi_processed_picture.html", "df/da2/struct_v_a_a_p_i_1_1_c_vaapi_processed_picture" ],
    [ "CVaapiRenderPicture", "d2/dc9/class_v_a_a_p_i_1_1_c_vaapi_render_picture.html", "d2/dc9/class_v_a_a_p_i_1_1_c_vaapi_render_picture" ],
    [ "CVaapiTexture", "db/dd1/class_v_a_a_p_i_1_1_c_vaapi_texture.html", "db/dd1/class_v_a_a_p_i_1_1_c_vaapi_texture" ],
    [ "CVideoSurfaces", "d6/dea/class_v_a_a_p_i_1_1_c_video_surfaces.html", "d6/dea/class_v_a_a_p_i_1_1_c_video_surfaces" ],
    [ "CVppPostproc", "df/d01/class_v_a_a_p_i_1_1_c_vpp_postproc.html", "df/d01/class_v_a_a_p_i_1_1_c_vpp_postproc" ],
    [ "InteropInfo", "df/d4b/struct_v_a_a_p_i_1_1_interop_info.html", "df/d4b/struct_v_a_a_p_i_1_1_interop_info" ],
    [ "IVaapiWinSystem", "d2/d2e/class_v_a_a_p_i_1_1_i_vaapi_win_system.html", "d2/d2e/class_v_a_a_p_i_1_1_i_vaapi_win_system" ],
    [ "SDiMethods", "d2/d16/struct_v_a_a_p_i_1_1_s_di_methods.html", "d2/d16/struct_v_a_a_p_i_1_1_s_di_methods" ],
    [ "ReadyToDispose", "d8/d70/namespace_v_a_a_p_i.html#a8e52947d442a779e9db1281710d4605f", null ],
    [ "VaErrorCallback", "d8/d70/namespace_v_a_a_p_i.html#a4b2ab640f0725b3c76b6bc533f09c7f5", null ],
    [ "VaInfoCallback", "d8/d70/namespace_v_a_a_p_i.html#afcc11b25d3acb17b4778ea9d084b06dc", null ]
];