var namespace_c_o_n_t_e_x_t_m_e_n_u =
[
    [ "CAddonInfo", "d3/dfd/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_addon_info.html", "d3/dfd/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_addon_info" ],
    [ "CAddonSettings", "d5/dac/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_addon_settings.html", "d5/dac/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_addon_settings" ],
    [ "CAddRemoveFavourite", "dc/d05/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_add_remove_favourite.html", "dc/d05/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_add_remove_favourite" ],
    [ "CAlbumInfo", "df/d26/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_album_info.html", "df/d26/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_album_info" ],
    [ "CArtistInfo", "dd/d10/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_artist_info.html", "dd/d10/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_artist_info" ],
    [ "CCheckForUpdates", "d2/d5a/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_check_for_updates.html", "d2/d5a/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_check_for_updates" ],
    [ "CChooseThumbnailForFavourite", "d0/de8/class_c_o_n_t_e_x_t_m_e_n_u_1_1_c_choose_thumbnail_for_favourite.html", "d0/de8/class_c_o_n_t_e_x_t_m_e_n_u_1_1_c_choose_thumbnail_for_favourite" ],
    [ "CDisableAddon", "d0/d7c/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_disable_addon.html", "d0/d7c/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_disable_addon" ],
    [ "CEjectDisk", "d5/d40/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_eject_disk.html", "d5/d40/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_eject_disk" ],
    [ "CEjectDrive", "d8/dcb/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_eject_drive.html", "d8/dcb/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_eject_drive" ],
    [ "CEnableAddon", "da/dbf/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_enable_addon.html", "da/dbf/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_enable_addon" ],
    [ "CEpisodeInfo", "d6/dbd/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_episode_info.html", "d6/dbd/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_episode_info" ],
    [ "CFavouriteContextMenuAction", "de/d26/class_c_o_n_t_e_x_t_m_e_n_u_1_1_c_favourite_context_menu_action.html", "de/d26/class_c_o_n_t_e_x_t_m_e_n_u_1_1_c_favourite_context_menu_action" ],
    [ "CMarkUnWatched", "df/d5d/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_mark_un_watched.html", "df/d5d/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_mark_un_watched" ],
    [ "CMarkWatched", "d7/dbc/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_mark_watched.html", "d7/dbc/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_mark_watched" ],
    [ "CMovieInfo", "d9/d6f/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_movie_info.html", "d9/d6f/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_movie_info" ],
    [ "CMusicInfo", "d7/d16/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_music_info.html", "d7/d16/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_music_info" ],
    [ "CMusicVideoInfo", "db/df7/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_music_video_info.html", "db/df7/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_music_video_info" ],
    [ "CPlay", "d2/d0f/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_play.html", "d2/d0f/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_play" ],
    [ "CPlayAndQueue", "d7/d4c/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_play_and_queue.html", "d7/d4c/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_play_and_queue" ],
    [ "CPlayNext", "dd/dbe/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_play_next.html", "dd/dbe/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_play_next" ],
    [ "CQueue", "d0/d5e/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_queue.html", "d0/d5e/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_queue" ],
    [ "CRemoveFavourite", "d1/d94/class_c_o_n_t_e_x_t_m_e_n_u_1_1_c_remove_favourite.html", "d1/d94/class_c_o_n_t_e_x_t_m_e_n_u_1_1_c_remove_favourite" ],
    [ "CRemoveResumePoint", "df/d3b/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_remove_resume_point.html", "df/d3b/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_remove_resume_point" ],
    [ "CRenameFavourite", "d6/d77/class_c_o_n_t_e_x_t_m_e_n_u_1_1_c_rename_favourite.html", "d6/d77/class_c_o_n_t_e_x_t_m_e_n_u_1_1_c_rename_favourite" ],
    [ "CResume", "d2/db1/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_resume.html", "d2/db1/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_resume" ],
    [ "CSongInfo", "da/d0b/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_song_info.html", "da/d0b/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_song_info" ],
    [ "CTVShowInfo", "df/dab/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_t_v_show_info.html", "df/dab/struct_c_o_n_t_e_x_t_m_e_n_u_1_1_c_t_v_show_info" ],
    [ "CVideoInfo", "db/da8/class_c_o_n_t_e_x_t_m_e_n_u_1_1_c_video_info.html", "db/da8/class_c_o_n_t_e_x_t_m_e_n_u_1_1_c_video_info" ],
    [ "LoopFrom", "dc/dd3/namespace_c_o_n_t_e_x_t_m_e_n_u.html#a01afc87daa2420e1598a45b4718bd769", null ],
    [ "ShowFor", "dc/dd3/namespace_c_o_n_t_e_x_t_m_e_n_u.html#a2a7e83a4289f1767fd6d23e9c1be20d9", null ]
];